export const INIT_CART = 'app/CART/INIT_CART';
export const INIT_CART_SUCCESS = 'app/CART/INIT_CART_SUCCESS';
export const INIT_CART_ERROR = 'app/CART/INIT_CART_SUCCESS';

export const CHANGE_CART = 'app/CART/CHANGE_CART';
export const CHANGE_CART_SUCCESS = 'app/CART/CHANGE_CART_SUCCESS';
export const CHANGE_CART_ERROR = 'app/CART/CHANGE_CART_SUCCESS';

export const GET_CART = 'app/CART/GET_CART';
export const GET_CART_SUCCESS = 'app/CART/GET_CART_SUCCESS';
export const GET_CART_ERROR = 'app/CART/GET_CART_ERROR';
