export const LOAD_LIST_LAYOUT = 'app/LAYOUT/LOAD_LIST';
export const LOAD_LIST_LAYOUT_SUCCESS = 'app/LAYOUT/LOAD_LIST_SUCCESS';
export const LOAD_LIST_LAYOUT_ERROR = 'app/LAYOUT/LOAD_LIST_ERROR';

export const CREATE_LAYOUT = 'app/LAYOUT/CREATE';
export const CREATE_LAYOUT_SUCCESS = 'app/LAYOUT/CREATE_SUCCESS';
export const CREATE_LAYOUT_ERROR = 'app/LAYOUT/CREATE_ERROR';

export const EDIT_LAYOUT = 'app/LAYOUT/EDIT';
export const EDIT_LAYOUT_SUCCESS = 'app/LAYOUT/EDIT_SUCCESS';
export const EDIT_LAYOUT_ERROR = 'app/LAYOUT/EDIT_ERROR';

export const DELETE_LAYOUT = 'app/LAYOUT/DELETE';
export const DELETE_LAYOUT_SUCCESS = 'app/LAYOUT/DELETE_SUCCESS';
export const DELETE_LAYOUT_ERROR = 'app/LAYOUT/DELETE_ERROR';
