export const LOAD_LIST_PACKAGE = 'app/PACKAGE/LOAD_LIST';
export const LOAD_LIST_PACKAGE_SUCCESS = 'app/PACKAGE/LOAD_LIST_SUCCESS';
export const LOAD_LIST_PACKAGE_ERROR = 'app/PACKAGE/LOAD_LIST_ERROR';

export const CREATE_PACKAGE = 'app/PACKAGE/CREATE_PACKAGE';
export const CREATE_PACKAGE_SUCCESS = 'app/PACKAGE/CREATE_PACKAGE_SUCCESS';
export const CREATE_PACKAGE_ERROR = 'app/PACKAGE/CREATE_PACKAGE_ERROR';
