export const LOAD_LIST_PRODUCT = 'app/PRODUCT/LOAD_LIST';
export const LOAD_LIST_PRODUCT_SUCCESS = 'app/PRODUCT/LOAD_LIST_SUCCESS';
export const LOAD_LIST_PRODUCT_ERROR = 'app/PRODUCT/LOAD_LIST_ERROR';

export const CREATE_PRODUCT = 'app/PRODUCT/CREATE_PRODUCT';
export const CREATE_PRODUCT_SUCCESS = 'app/PRODUCT/CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_ERROR = 'app/PRODUCT/CREATE_PRODUCT_ERROR';

export const EDIT_PRODUCT = 'app/PRODUCT/EDIT_PRODUCT';
export const EDIT_PRODUCT_SUCCESS = 'app/PRODUCT/EDIT_PRODUCT_SUCCESS';
export const EDIT_PRODUCT_ERROR = 'app/PRODUCT/EDIT_PRODUCT_ERROR';

export const DELETE_PRODUCT = 'app/PRODUCT/DELETE_PRODUCT';
export const DELETE_PRODUCT_SUCCESS = 'app/PRODUCT/DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_ERROR = 'app/PRODUCT/DELETE_PRODUCT_ERROR';
